server:
  port: 8090
spring:
  datasource:
    name: picadb
    url: jdbc:mysql://192.168.121.132:3307/picadb?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  check-config-location: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wechat_study.demo.entity

