package com.wechat_study.demo.entity;

public class ArticleResEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_resources.id
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_resources.url
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_resources.label
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    private String label;

    public ArticleResEntity(Integer id, String url, String label) {
        this.id = id;
        this.url = url;
        this.label = label;
    }

    public ArticleResEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_resources.id
     *
     * @return the value of article_resources.id
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_resources.id
     *
     * @param id the value for article_resources.id
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_resources.url
     *
     * @return the value of article_resources.url
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_resources.url
     *
     * @param url the value for article_resources.url
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_resources.label
     *
     * @return the value of article_resources.label
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_resources.label
     *
     * @param label the value for article_resources.label
     *
     * @mbggenerated Thu Aug 15 17:18:22 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}