package com.wechat_study.demo.entity;

public class LinkEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link_id
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    private String linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.kind
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.level
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.url
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.label
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    private String label;

    public LinkEntity(String linkId, String kind, Integer level, String url, String label) {
        this.linkId = linkId;
        this.kind = kind;
        this.level = level;
        this.url = url;
        this.label = label;
    }

    public LinkEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link_id
     *
     * @return the value of links.link_id
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link_id
     *
     * @param linkId the value for links.link_id
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId == null ? null : linkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.kind
     *
     * @return the value of links.kind
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.kind
     *
     * @param kind the value for links.kind
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.level
     *
     * @return the value of links.level
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.level
     *
     * @param level the value for links.level
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.url
     *
     * @return the value of links.url
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.url
     *
     * @param url the value for links.url
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.label
     *
     * @return the value of links.label
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.label
     *
     * @param label the value for links.label
     *
     * @mbggenerated Tue Aug 13 10:27:47 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}