package com.wechat_study.demo.entity;

public class ResTypeInfoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_type_info.idres_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    private Integer idresTypeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_type_info.type_name
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    private String typeName;

    public ResTypeInfoEntity(Integer idresTypeInfo, String typeName) {
        this.idresTypeInfo = idresTypeInfo;
        this.typeName = typeName;
    }

    public ResTypeInfoEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_type_info.idres_type_info
     *
     * @return the value of res_type_info.idres_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    public Integer getIdresTypeInfo() {
        return idresTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_type_info.idres_type_info
     *
     * @param idresTypeInfo the value for res_type_info.idres_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    public void setIdresTypeInfo(Integer idresTypeInfo) {
        this.idresTypeInfo = idresTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_type_info.type_name
     *
     * @return the value of res_type_info.type_name
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_type_info.type_name
     *
     * @param typeName the value for res_type_info.type_name
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}