package com.wechat_study.demo.entity;

public class UserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_records.openid
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_records.username
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_records.identity
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    private Integer identity;

    public UserEntity(String openid, String username, Integer identity) {
        this.openid = openid;
        this.username = username;
        this.identity = identity;
    }

    public UserEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_records.openid
     *
     * @return the value of users_records.openid
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_records.openid
     *
     * @param openid the value for users_records.openid
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_records.username
     *
     * @return the value of users_records.username
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_records.username
     *
     * @param username the value for users_records.username
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_records.identity
     *
     * @return the value of users_records.identity
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    public Integer getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_records.identity
     *
     * @param identity the value for users_records.identity
     *
     * @mbggenerated Wed Aug 14 17:57:29 CST 2019
     */
    public void setIdentity(Integer identity) {
        this.identity = identity;
    }
}