package com.wechat_study.demo.entity;

public class UserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CURRENT_CONNECTIONS
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    private Long currentConnections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.TOTAL_CONNECTIONS
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    private Long totalConnections;

    public UserEntity(String user, Long currentConnections, Long totalConnections) {
        this.user = user;
        this.currentConnections = currentConnections;
        this.totalConnections = totalConnections;
    }

    public UserEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER
     *
     * @return the value of users.USER
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER
     *
     * @param user the value for users.USER
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CURRENT_CONNECTIONS
     *
     * @return the value of users.CURRENT_CONNECTIONS
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    public Long getCurrentConnections() {
        return currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CURRENT_CONNECTIONS
     *
     * @param currentConnections the value for users.CURRENT_CONNECTIONS
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    public void setCurrentConnections(Long currentConnections) {
        this.currentConnections = currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.TOTAL_CONNECTIONS
     *
     * @return the value of users.TOTAL_CONNECTIONS
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    public Long getTotalConnections() {
        return totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.TOTAL_CONNECTIONS
     *
     * @param totalConnections the value for users.TOTAL_CONNECTIONS
     *
     * @mbggenerated Tue Aug 13 10:48:35 CST 2019
     */
    public void setTotalConnections(Long totalConnections) {
        this.totalConnections = totalConnections;
    }
}