package com.wechat_study.demo.mapping;

import com.wechat_study.demo.entity.ArticleResEntity;
import com.wechat_study.demo.entity.ArticleResEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface ArticleResEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int countByExample(ArticleResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int deleteByExample(ArticleResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int insert(ArticleResEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int insertSelective(ArticleResEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    List<ArticleResEntity> selectByExample(ArticleResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    ArticleResEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") ArticleResEntity record, @Param("example") ArticleResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByExample(@Param("record") ArticleResEntity record, @Param("example") ArticleResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleResEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resources
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByPrimaryKey(ArticleResEntity record);
}