package com.wechat_study.demo.mapping;

import com.wechat_study.demo.entity.CarouselResEntity;
import com.wechat_study.demo.entity.CarouselResEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface CarouselResEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int countByExample(CarouselResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int deleteByExample(CarouselResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int insert(CarouselResEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int insertSelective(CarouselResEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    List<CarouselResEntity> selectByExample(CarouselResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    CarouselResEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") CarouselResEntity record, @Param("example") CarouselResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int updateByExample(@Param("record") CarouselResEntity record, @Param("example") CarouselResEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int updateByPrimaryKeySelective(CarouselResEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel_resources
     *
     * @mbggenerated Tue Aug 13 15:34:30 CST 2019
     */
    int updateByPrimaryKey(CarouselResEntity record);
}