package com.wechat_study.demo.mapping;

import com.wechat_study.demo.entity.QuestionEntity;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionEntityMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbggenerated Mon Aug 12 18:21:59 CST 2019
     */
    int deleteByPrimaryKey(String questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbggenerated Mon Aug 12 18:21:59 CST 2019
     */
    int insert(QuestionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbggenerated Mon Aug 12 18:21:59 CST 2019
     */
    int insertSelective(QuestionEntity record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbggenerated Mon Aug 12 18:21:59 CST 2019
     */
    QuestionEntity selectByPrimaryKey(String questionId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbggenerated Mon Aug 12 18:21:59 CST 2019
     */
    int updateByPrimaryKeySelective(QuestionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbggenerated Mon Aug 12 18:21:59 CST 2019
     */
    int updateByPrimaryKey(QuestionEntity record);
}