package com.wechat_study.demo.mapping;

import com.wechat_study.demo.entity.ResTypeInfoEntity;
import com.wechat_study.demo.entity.ResTypeInfoEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface ResTypeInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int countByExample(ResTypeInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int deleteByExample(ResTypeInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int deleteByPrimaryKey(Integer idresTypeInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int insert(ResTypeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int insertSelective(ResTypeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    List<ResTypeInfoEntity> selectByExample(ResTypeInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    ResTypeInfoEntity selectByPrimaryKey(Integer idresTypeInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") ResTypeInfoEntity record, @Param("example") ResTypeInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByExample(@Param("record") ResTypeInfoEntity record, @Param("example") ResTypeInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByPrimaryKeySelective(ResTypeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_type_info
     *
     * @mbggenerated Fri Aug 16 11:43:36 CST 2019
     */
    int updateByPrimaryKey(ResTypeInfoEntity record);
}